### ISSUE TITLE
[BUG] Stav did an oopsie (1.20.1)

### ISSUE THREAD

**Issue by NukolLodda** [StavWasPlayZ/Genshin-Instruments-Fabric#4]
There's an issue with playing music discs in the normal jukebox. This happens when I try and place the custom discs in to the normal jukebox and nothing plays. I was wondering whether this was an issue to be fixed or if this was intentional but if it is a bug, I suspect that you might need to register the custom discs to be part of the minecraft/music_discs tag followed by a sounds.json file in which it needs to be updated to contain the custom sounds (though I'm not sure whether it can be placed as an ogg) in the assets folder.

**Comment by StavWasPlayZ** [comment]
Hey there!

I'm confused - are you speaking of Even More Instrument's records? Or is there an issue in Genshin Instruments that causes Minecraft vanilla discs to not work?  
Because this is the Genshin Instruments repository..

Because of it's the former, I'm afraid this is by design... 😅  
Records are to be used in Loopers, and vanilla disks, well - in Jukeboxes.

I'd be glad if you could confirm or extend on further on the issue.

**Comment by NukolLodda** [comment]
wait wrong email, ignore this message

**Comment by NukolLodda** [comment]
well, now that you mention it this way, there's no error at all actually,
cause I initially asked a question since I wasn't sure whether this design
was intentional or not.

**Comment by StavWasPlayZ** [comment]
Then no issues.
